---
dist: trusty
language: python
cache: pip
python: "2.7"

# Use isolated build instance
sudo: required

env:
  global:
    - ANSIBLE_CONFIG=tests/ansible.cfg
  matrix:
    - RUN="shellcheck yamlcheck syntax" SITE="global_vars/default-site.yml"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-pip python-dev ca-certificates shellcheck -qq

install:
  - pip install ansible==2.4.0.0
  - pip install urllib3 yamllint
  - ansible --version

script:
  - ./tests/tests.sh
