---
streisand_gateway_url: "https://{{ streisand_ipv4_address }}"

streisand_gateway_htpasswd_file: "/etc/nginx/htpasswd"
streisand_gateway_password_file: "/etc/nginx/gateway-password.txt"
streisand_gateway_password_localpath: "../{{ streisand_local_directory }}/gateway-password.txt"

streisand_gateway_markdown_firewall_information: "/tmp/{{ streisand_server_name }}-firewall-information.md"
streisand_gateway_html_firewall_information: "/tmp/{{ streisand_server_name }}-firewall-information.html"

streisand_gateway_markdown_instructions: "/tmp/{{ streisand_server_name }}.md"
streisand_gateway_html_instructions: "/tmp/{{ streisand_server_name }}.html"

streisand_gateway_markdown_index: "{{ streisand_gateway_location }}/index.md"
streisand_gateway_html_index: "{{ streisand_gateway_location }}/index.html"
streisand_gateway_ca_file: "{{ streisand_gateway_location }}/ca.pem"

nginx_internal_hidden_service_address: "127.0.0.1:8181"
