---
- name: Collect diagnostic information in case there is a problem
# =========================================
  hosts: localhost
  gather_facts: no

  tasks:
    - name: "Determine the git revision of the current Streisand clone"
      command: git rev-parse HEAD
      register: streisand_diagnostics_git_rev
      changed_when: False

    - name: "debug shit"
      debug:
        var: streisand_diagnostics_git_rev

